spring:
  datasource:
    # 配置自带数据库的相对路径
    url: jdbc:mysql://chat2db:RrF33VNHQg8BBKlH!@l-overseas-app-base-rw-gd-mysql.hw.tanjingpaas.com:3306/chat2db
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  用于数据库表结构版本管理
  flyway:
    locations: classpath:db/mysql-migration
# 端口号
server:
  port: 10824

chat2db:
  gateway:
    base-url: http://test.sqlgpt.cn/gateway
    model-base-url: http://test.sqlgpt.cn/gateway
